moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  arm_controller:
    action_ns: /arm_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3

  gripper_controller:
    action_ns: /gripper_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint4
      - joint5
